name: deploy server2 web and data monitoring

on: # 아래 job을 실행시킬 상황
  push:
    paths:
      - 'CorpAnalytica_Web/**'
      - 'data-monitoring/**'
      - 'docker-compose/server2_web_data-monitoring/**'
    branches:
      - main

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: excuting remote ssh commands
        uses: appleboy/ssh-action@v0.1.6 # ssh 접속하는 오픈소스
        with:
          host: ${{ secrets.REMOTE_IP_SERVER2 }} # 인스턴스 IP
          username: ${{ secrets.REMOTE_USER }} # 우분투 아이디
          key: ${{ secrets.REMOTE_PRIVATE_KEY }} # ec2 instance pem key
          port: ${{ secrets.REMOTE_SSH_PORT }} # 접속포트
          script: | # 실행할 스크립트
            sh deploy.sh